services:
  fileagent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8000
      - HOST="0.0.0.0"
      - FILE=test
      - DIRECTORY=/app/custom
    hostname: fileagent
    network_mode: "host"
    ports:
      - "8000:8000"
    volumes:
      - custom_data:/app/custom

volumes:
  custom_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: ./snort/volumes/custom
      device: .
